#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019,2020 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -d /etc/elasticsearch ] && [ -d /nsm/logstash ] && [ -d /var/log/kibana ] && [ -f /etc/cron.d/curator-delete ] && [ -f /usr/sbin/so-common ] && [ -f /etc/nsm/securityonion.conf ] && [ -x /usr/sbin/so-elastic-configure ] ; then

	. /usr/sbin/so-common
	. /etc/nsm/securityonion.conf

	if [ "$ELASTICSEARCH_ENABLED" = "yes" ] || [ "$LOGSTASH_ENABLED" = "yes" ] || [ "$KIBANA_ENABLED" = "yes" ] || [ "$FREQ_SERVER_ENABLED" = "yes" ] || [ "$DOMAIN_STATS_ENABLED" = "yes" ] || [ "$ELASTALERT_ENABLED" = "yes" ] || [ "$CURATOR_ENABLED" = "yes" ]; then

		echo "One or more Elastic components enabled.  Updating!"
		/usr/sbin/so-elastic-configure || echo "Error updating Elastic config."

	fi

fi
