#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019,2020 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

SOCONF="/etc/nsm/securityonion.conf"
ELASTICONF="${SRC}/etc/securityonion-elastic.conf"

# Specify Docker network and create it
header "Creating Docker network for Elastic Stack"
DOCKERNET=`grep 'DOCKERNET' ${ELASTICONF} | cut -d "=" -f2 | sed 's/"//g'`
if pgrep -f docker > /dev/null; then
        docker network create ${DOCKERNET} --driver=bridge >/dev/null 2>&1
        echo ${DOCKERNET}
fi

# Docker daemon.json conflict #1674
# https://github.com/Security-Onion-Solutions/security-onion/issues/1674
DAEMONJSON=/etc/docker/daemon.json
if [ -f $DAEMONJSON ]; then
	echo "$DAEMONJSON exists."
	if [ "0bcf8587dea814c9b712064c28da3d82" = $(md5sum $DAEMONJSON | awk '{print $1}') ]; then
		echo "$DAEMONJSON is original version with default values."
		rm -f $DAEMONJSON
		echo "Removed $DAEMONJSON."
	else
		. ${SOCONF}
		if [ -n ${DOCKER_BRIDGE} ]; then
			DOCKER_DAEMON_BRIDGE=`grep bip $DAEMONJSON | awk '{print $2}' | sed 's/"//g'`
			if [ "${DOCKER_BRIDGE}" != "${DOCKER_DAEMON_BRIDGE}" ]; then
				sed -i "s|\"bip\": .*|\"bip\": \"${DOCKER_BRIDGE}\"|" $DAEMONJSON
				service docker restart
			fi
		fi
	fi
fi
